/** Declaration file generated by dts-gen */

interface JSONReturn {
	content: string;
	meta: {
		[key: string]: string;
	};
}

declare module 'mark-twain' {
	function MT(markdown: string): JSONReturn;

	export default MT;
}
